"""application reminded_at

Revision ID: 1d2c6d342453
Revises: 81c4c78d875d
Create Date: 2026-08-15 17:21:51.900127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2c6d342453'
down_revision: Union[str, None] = '81c4c78d875d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'reminded_at')
    # ### end Alembic commands ###
