"""user reminders_enabled

Revision ID: 6c7903dbc6aa
Revises: 1d2c6d342453
Create Date: 2026-08-15 17:47:53.285040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7903dbc6aa'
down_revision: Union[str, None] = '1d2c6d342453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-adjusted. Autogenerate emits a plain NOT NULL column, which fails
    # outright against rows that already exist.
    op.add_column(
        'users',
        sa.Column(
            'reminders_enabled', sa.Boolean(), nullable=False, server_default=sa.true()
        ),
    )
    # Opt-out, not opt-in: everyone who already has an account keeps reminders,
    # and can turn them off from the settings page or any digest.
    op.execute('UPDATE users SET reminders_enabled = true')
    # Drop the server default so new rows take theirs from the model instead,
    # keeping the rule in one place.
    op.alter_column('users', 'reminders_enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminders_enabled')
    # ### end Alembic commands ###
