"""application board: optional description, apply_by, one card per job

Revision ID: 70b7bc510755
Revises: 4fdba7a05289
Create Date: 2026-08-12 14:37:17.457335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70b7bc510755'
down_revision: Union[str, None] = '4fdba7a05289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_applications_user_job', 'applications', ['user_id', 'job_id'])
    op.add_column('jobs', sa.Column('apply_by', sa.Date(), nullable=True))
    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Hand-added: by the time this runs, tracking-only jobs will have a null
    # description, and restoring NOT NULL would abort on them. An empty string
    # is the closest lossless equivalent under the old constraint.
    op.execute("UPDATE jobs SET description = '' WHERE description IS NULL")

    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('jobs', 'apply_by')
    op.drop_constraint('uq_applications_user_job', 'applications', type_='unique')
    # ### end Alembic commands ###
