"""tailoring refine lineage

Revision ID: 81c4c78d875d
Revises: 70b7bc510755
Create Date: 2026-08-13 15:00:01.924039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81c4c78d875d'
down_revision: Union[str, None] = '70b7bc510755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailorings', sa.Column('refine_of_id', sa.Uuid(), nullable=True))
    op.add_column('tailorings', sa.Column('feedback', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('tailorings', sa.Column('feedback_notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tailorings_refine_of_id'), 'tailorings', ['refine_of_id'], unique=False)
    # Named explicitly: autogenerate emitted None, which Postgres would
    # auto-name and the downgrade below could then never drop.
    op.create_foreign_key(
        'fk_tailorings_refine_of_id',
        'tailorings', 'tailorings', ['refine_of_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tailorings_refine_of_id', 'tailorings', type_='foreignkey')
    op.drop_index(op.f('ix_tailorings_refine_of_id'), table_name='tailorings')
    op.drop_column('tailorings', 'feedback_notes')
    op.drop_column('tailorings', 'feedback')
    op.drop_column('tailorings', 'refine_of_id')
    # ### end Alembic commands ###
