"""add email verification

Revision ID: 903ef2eabecc
Revises: 0c2f605f527b
Create Date: 2026-08-09 11:16:23.999036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903ef2eabecc'
down_revision: Union[str, None] = '0c2f605f527b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token_hash'), 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-adjusted. Autogenerate emitted a plain NOT NULL column, which fails
    # outright on a table that already has rows — there is no value to put in
    # them.
    op.add_column(
        'users',
        sa.Column(
            'is_verified', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )

    # Existing accounts were created before verification existed. Leaving them
    # unverified would lock every current user out of an app they were already
    # using, so they are grandfathered in. Only new signups must confirm.
    op.execute('UPDATE users SET is_verified = true')

    # Drop the server default now the backfill is done: new rows should get
    # their default from the model (False), so the rule lives in one place
    # rather than being split between Python and the schema.
    op.alter_column('users', 'is_verified', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token_hash'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
