"""application source interview date apply prompt

Revision ID: c6ef2c5d06ae
Revises: 6c7903dbc6aa
Create Date: 2026-08-16 11:24:06.049719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ef2c5d06ae'
down_revision: Union[str, None] = '6c7903dbc6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SOURCE_VALUES = (
    'UNKNOWN', 'REFERRAL', 'JOB_BOARD', 'COMPANY_SITE', 'RECRUITER', 'OTHER',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Hand-added, and the reason the first attempt failed in production:
    # SQLAlchemy only emits CREATE TYPE for an Enum as part of create_table.
    # Inside add_column it renders the type name and assumes it already exists,
    # so on Postgres the ALTER fails with "type does not exist". Every earlier
    # enum in this schema arrived with its table, which is why none hit this.
    sa.Enum(*SOURCE_VALUES, name='application_source').create(
        op.get_bind(), checkfirst=True
    )

    # Autogenerate emits a plain NOT NULL column, which fails against rows that
    # already exist; existing cards simply have an unrecorded source, which is
    # exactly what UNKNOWN means.
    op.add_column(
        'applications',
        sa.Column(
            'source',
            sa.Enum(*SOURCE_VALUES, name='application_source'),
            nullable=False,
            server_default='UNKNOWN',
        ),
    )
    op.alter_column('applications', 'source', server_default=None)
    op.add_column('applications', sa.Column('interview_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('apply_prompt_dismissed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'apply_prompt_dismissed_at')
    op.drop_column('applications', 'interview_at')
    op.drop_column('applications', 'source')
    # Autogenerate creates the enum type but never drops it, so a downgrade then
    # upgrade would fail with "type already exists".
    sa.Enum(name='application_source').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
