import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'

import { Button, Card, EmptyState, ErrorNote, Spinner } from '../components/ui'
import { api } from '../lib/api'
import type { JobDetail, Resume, Tailoring, TailoringDetail } from '../lib/types'

function errorMessage(err: unknown): string {
  return err instanceof Error ? err.message : 'Something went wrong.'
}

function scoreTone(score: number): string {
  if (score >= 75) return 'text-emerald-600 dark:text-emerald-400'
  if (score >= 50) return 'text-amber-600 dark:text-amber-400'
  return 'text-red-600 dark:text-red-400'
}

function MatchScore({ score }: { score: number | null }) {
  if (score === null) {
    return (
      <p className="text-sm text-slate-500 dark:text-slate-400">
        No match score returned.
      </p>
    )
  }

  return (
    <div>
      <p className={`text-4xl font-semibold tabular-nums ${scoreTone(score)}`}>
        {Math.round(score)}
        <span className="text-lg font-normal text-slate-400">/100</span>
      </p>
      <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
        How well your experience fit this role <em>before</em> tailoring.
      </p>
    </div>
  )
}

function TailoringResult({
  tailoring,
  onDownload,
  downloading,
}: {
  tailoring: TailoringDetail
  onDownload: () => void
  downloading: boolean
}) {
  if (tailoring.status === 'failed') {
    return (
      <Card>
        <h2 className="mb-2 font-semibold">Tailoring failed</h2>
        <ErrorNote>{tailoring.error ?? 'Unknown error.'}</ErrorNote>
      </Card>
    )
  }

  return (
    <div className="space-y-6">
      <div className="grid gap-6 sm:grid-cols-2">
        <Card>
          <h2 className="mb-3 font-semibold">Match score</h2>
          <MatchScore score={tailoring.match_score} />
        </Card>

        <Card>
          <h2 className="mb-3 font-semibold">Gaps</h2>
          {tailoring.missing_keywords?.length ? (
            <>
              <ul className="flex flex-wrap gap-1.5">
                {tailoring.missing_keywords.map((keyword) => (
                  <li
                    key={keyword}
                    className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-800 dark:bg-amber-950/50 dark:text-amber-300"
                  >
                    {keyword}
                  </li>
                ))}
              </ul>
              <p className="mt-3 text-xs text-slate-500 dark:text-slate-400">
                Requirements your resume genuinely does not cover. These were
                deliberately not invented.
              </p>
            </>
          ) : (
            <p className="text-sm text-slate-500 dark:text-slate-400">
              No significant gaps identified.
            </p>
          )}
        </Card>
      </div>

      {tailoring.changes?.length ? (
        <Card>
          <h2 className="mb-3 font-semibold">What changed</h2>
          <ul className="space-y-2">
            {tailoring.changes.map((change) => (
              <li
                key={change}
                className="flex gap-2 text-sm text-slate-700 dark:text-slate-300"
              >
                <span aria-hidden className="text-indigo-500">
                  •
                </span>
                {change}
              </li>
            ))}
          </ul>
        </Card>
      ) : null}

      <Card>
        <div className="mb-3 flex items-center justify-between gap-3">
          <h2 className="font-semibold">Tailored resume</h2>
          <Button onClick={onDownload} loading={downloading}>
            Download .docx
          </Button>
        </div>
        <pre className="max-h-96 overflow-auto rounded-lg bg-slate-50 p-4 text-xs leading-relaxed whitespace-pre-wrap text-slate-800 dark:bg-slate-950 dark:text-slate-200">
          {tailoring.tailored_text}
        </pre>
        {tailoring.model && (
          <p className="mt-2 text-xs text-slate-400">
            Generated by {tailoring.model}
          </p>
        )}
      </Card>
    </div>
  )
}

export function JobPage() {
  const { jobId = '' } = useParams()

  const [job, setJob] = useState<JobDetail | null>(null)
  const [resumes, setResumes] = useState<Resume[]>([])
  const [history, setHistory] = useState<Tailoring[]>([])
  const [selected, setSelected] = useState<TailoringDetail | null>(null)
  const [resumeId, setResumeId] = useState<string>('')

  const [loading, setLoading] = useState(true)
  const [tailoring, setTailoring] = useState(false)
  const [downloading, setDownloading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [showDescription, setShowDescription] = useState(false)

  const load = useCallback(async () => {
    setError(null)
    try {
      const [jobDetail, resumeList, tailoringList] = await Promise.all([
        api.jobs.get(jobId),
        api.resumes.list(),
        api.tailorings.listForJob(jobId),
      ])
      setJob(jobDetail)
      setResumes(resumeList)
      setHistory(tailoringList)
      setResumeId(resumeList.find((r) => r.is_default)?.id ?? resumeList[0]?.id ?? '')

      // Show the most recent successful run so a refresh doesn't lose results.
      const latest = tailoringList.find((t) => t.status === 'succeeded')
      if (latest) setSelected(await api.tailorings.get(latest.id))
    } catch (err) {
      setError(errorMessage(err))
    } finally {
      setLoading(false)
    }
  }, [jobId])

  useEffect(() => {
    void load()
  }, [load])

  async function handleTailor() {
    setError(null)
    setTailoring(true)
    try {
      const result = await api.tailorings.create(jobId, resumeId || undefined)
      setSelected(result)
      setHistory(await api.tailorings.listForJob(jobId))
    } catch (err) {
      setError(errorMessage(err))
      // A failed run is still recorded server-side — reflect that in history.
      try {
        setHistory(await api.tailorings.listForJob(jobId))
      } catch {
        // Ignore: the primary error is already shown.
      }
    } finally {
      setTailoring(false)
    }
  }

  async function handleDownload() {
    if (!selected) return
    setDownloading(true)
    try {
      await api.tailorings.download(selected.id)
    } catch (err) {
      setError(errorMessage(err))
    } finally {
      setDownloading(false)
    }
  }

  if (loading) return <Spinner label="Loading job…" />

  if (!job) {
    return (
      <div className="space-y-4">
        <ErrorNote>{error ?? 'Job not found.'}</ErrorNote>
        <Link to="/" className="text-sm text-indigo-600 dark:text-indigo-400">
          ← Back to dashboard
        </Link>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <Link
          to="/"
          className="text-sm text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white"
        >
          ← Dashboard
        </Link>
        <h1 className="mt-2 text-2xl font-semibold tracking-tight">{job.title}</h1>
        <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
          {job.company}
          {job.location ? ` · ${job.location}` : ''}
        </p>
      </div>

      <Card>
        <div className="flex flex-wrap items-end gap-3">
          <label className="flex-1">
            <span className="mb-1.5 block text-sm font-medium text-slate-700 dark:text-slate-300">
              Resume to tailor
            </span>
            <select
              value={resumeId}
              onChange={(e) => setResumeId(e.target.value)}
              disabled={resumes.length === 0}
              className="block w-full rounded-md border-0 bg-white px-3 py-2 text-sm ring-1 ring-slate-300 focus:ring-2 focus:ring-indigo-600 dark:bg-slate-900 dark:ring-slate-700"
            >
              {resumes.length === 0 && <option value="">No resumes uploaded</option>}
              {resumes.map((resume) => (
                <option key={resume.id} value={resume.id}>
                  {resume.name}
                  {resume.is_default ? ' (default)' : ''}
                </option>
              ))}
            </select>
          </label>

          <Button
            onClick={handleTailor}
            loading={tailoring}
            disabled={resumes.length === 0}
          >
            {selected ? 'Tailor again' : 'Tailor my resume'}
          </Button>
        </div>

        {tailoring && (
          <p className="mt-3 text-sm text-slate-500 dark:text-slate-400">
            Rewriting against this posting — this usually takes 10–20 seconds.
          </p>
        )}

        {resumes.length === 0 && (
          <p className="mt-3 text-sm text-slate-500 dark:text-slate-400">
            Upload a resume on the{' '}
            <Link to="/" className="text-indigo-600 dark:text-indigo-400">
              dashboard
            </Link>{' '}
            first.
          </p>
        )}

        <ErrorNote>{error}</ErrorNote>
      </Card>

      <Card>
        <button
          onClick={() => setShowDescription((v) => !v)}
          className="flex w-full items-center justify-between text-left font-semibold"
        >
          Job description
          <span aria-hidden className="text-sm font-normal text-slate-400">
            {showDescription ? 'Hide' : 'Show'}
          </span>
        </button>
        {showDescription && (
          <p className="mt-3 text-sm leading-relaxed whitespace-pre-wrap text-slate-700 dark:text-slate-300">
            {job.description}
          </p>
        )}
      </Card>

      {selected ? (
        <TailoringResult
          tailoring={selected}
          onDownload={handleDownload}
          downloading={downloading}
        />
      ) : (
        <Card>
          <EmptyState>
            No tailored version yet. Pick a resume and tailor it for this role.
          </EmptyState>
        </Card>
      )}

      {history.length > 1 && (
        <Card>
          <h2 className="mb-3 font-semibold">Previous runs</h2>
          <ul className="divide-y divide-slate-200 dark:divide-slate-800">
            {history.map((run) => (
              <li key={run.id} className="flex items-center gap-3 py-2.5">
                <span className="text-sm text-slate-600 dark:text-slate-400">
                  {new Date(run.created_at).toLocaleString()}
                </span>
                <span
                  className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                    run.status === 'succeeded'
                      ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300'
                      : 'bg-red-50 text-red-700 dark:bg-red-950/50 dark:text-red-300'
                  }`}
                >
                  {run.status}
                </span>
                {run.match_score !== null && (
                  <span className="text-sm tabular-nums text-slate-500">
                    {Math.round(run.match_score)}/100
                  </span>
                )}
                <div className="ml-auto">
                  {run.status === 'succeeded' && run.id !== selected?.id && (
                    <Button
                      variant="secondary"
                      onClick={async () => setSelected(await api.tailorings.get(run.id))}
                    >
                      View
                    </Button>
                  )}
                </div>
              </li>
            ))}
          </ul>
        </Card>
      )}
    </div>
  )
}
